name: Automatic Word Drop

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

jobs:
  run_word_drop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project Violet (Repo A)
        uses: actions/checkout@v3
        with:
          repository: kvsri007/project_violet
          path: violet

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd violet
          pip install -r requirements.txt

      - name: Create credentials.json
        run: echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > credentials.json
        working-directory: violet

      - name: Create token.json
        run: echo "${{ secrets.GOOGLE_TOKEN_JSON }}" > token.json
        working-directory: violet

      - name: Run the script
        run: python main.py
        working-directory: violet
